### ISSUE TITLE
Fine-tune VGA timing

### ISSUE THREAD

**Issue by sy2002** [sy2002/zxuno4mega65#14]
Deft reported that the VGA output is not working on all VGA monitors

**Comment by sy2002** [comment]
Jazzcat on MEGA65 Discord reported, that it does not work on a Acer G225HQ.

**Comment by aowendev** [comment]
There are some minor changes to the VGA in this fork that may be relevant: https://github.com/Utodev/smartROM

**Comment by sy2002** [comment]
Fine-tuned VGA timing in Version 1.0
