### ISSUE TITLE
ESC won't open file browser

### ISSUE THREAD

**Issue by Lossehelin78** [sy2002/zxuno4mega65#19]
Hello,

I'm using the latest R6 version of ZX Uno but I'm not able to use the ESC key on the Mega65. Am I missing something?

Thanks,

**Comment by sy2002** [comment]
Hi @Lossehelin78 , did you work through the tutorial: https://github.com/sy2002/zxuno4mega65/wiki/Getting-Started

In particular: Did you install the mandatory EXDOS files as described here:
https://github.com/sy2002/zxuno4mega65/wiki/Getting-Started#1-prepare-an-sd-card

**Comment by Lossehelin78** [comment]
Hello,

I feel so embarrassed. I’ve missed the tutorial. Working now!

Thanks for your kind reply,

Best regards,

**Comment by sy2002** [comment]
No worries @Lossehelin78 - thank you for your feedback and have fun with the core :-)  I am closing this issue.
