### ISSUE TITLE
Support SOXZ bootloader

### ISSUE THREAD

**Issue by sy2002** [sy2002/zxuno4mega65#7]
Support SOXZ bootloader, including Spectrum ROM loading from SD Card

**Comment by aowendev** [comment]
Sadly, I don't think I'm ever going to get the time to work on SOXZ. However, there is a bootloader based on the same branch of the ZX-Uno core as your port. It should be possible to merge with your fork: https://github.com/Utodev/smartROM

I tried a merge and I successfully built and installed the bit stream, but it doesn't work, and I have no idea how to debug it.
